/**
 * pdfExport.ts — Browser-native PDF export using window.print()
 * No jspdf / jspdf-autotable dependency required.
 * Opens a styled print window that the user saves as PDF via the browser dialog.
 */

import { Trip } from "@/types/trip";
import { Driver } from "@/types/driver";

// ─── Helpers ──────────────────────────────────────────────────────────────────

const formatCurrency = (val: number) =>
  new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(val);

const formatDate = (dateStr?: string | null) => {
  if (!dateStr) return "—";
  try {
    const d = new Date(dateStr);
    if (isNaN(d.getTime())) return "—";
    return d.toISOString().split("T")[0];
  } catch {
    return "—";
  }
};

// ─── Core print engine ────────────────────────────────────────────────────────

function printReport(
  title: string,
  headers: string[],
  rows: string[][],
  filename: string,
  filters?: Record<string, string>
) {
  const now = new Date();
  const dateStr = now.toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" });
  const timeStr = now.toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit" });

  const activeFilters = filters
    ? Object.entries(filters)
        .filter(([, v]) => v && v !== "ALL" && v.trim() !== "")
        .map(([k, v]) => `<span class="filter-chip">${k}: <strong>${v}</strong></span>`)
        .join("")
    : "";

  const tableRows = rows
    .map(
      (row, i) =>
        `<tr class="${i % 2 === 0 ? "even" : "odd"}">${row.map((cell) => `<td>${cell}</td>`).join("")}</tr>`
    )
    .join("");

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>${title} — TransitOps</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 11px; color: #27272a; background: #fff; padding: 24px 28px; }
    .header { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 2px solid #27272a; padding-bottom: 10px; margin-bottom: 14px; }
    .brand { font-size: 20px; font-weight: 700; letter-spacing: -0.5px; color: #18181b; }
    .brand span { font-size: 9px; font-weight: 400; color: #71717a; display: block; margin-top: 2px; letter-spacing: 0; }
    .meta { text-align: right; color: #71717a; font-size: 9px; line-height: 1.7; }
    h1 { font-size: 15px; font-weight: 700; color: #18181b; margin-bottom: 8px; text-transform: uppercase; letter-spacing: 0.5px; }
    .summary { display: flex; gap: 16px; margin-bottom: 12px; align-items: center; flex-wrap: wrap; }
    .summary-item { font-size: 9.5px; color: #52525b; }
    .filter-chip { display: inline-block; background: #f4f4f5; border-radius: 4px; padding: 2px 6px; margin: 0 3px; font-size: 9px; }
    table { width: 100%; border-collapse: collapse; font-size: 9.5px; }
    thead tr { background: #27272a; color: #fff; }
    thead th { padding: 7px 8px; text-align: left; font-weight: 600; letter-spacing: 0.3px; white-space: nowrap; }
    tbody tr.even { background: #fafafa; }
    tbody tr.odd { background: #fff; }
    tbody td { padding: 6px 8px; color: #3f3f46; border-bottom: 1px solid #f4f4f5; vertical-align: middle; }
    .footer { margin-top: 18px; border-top: 1px solid #e4e4e7; padding-top: 8px; display: flex; justify-content: space-between; color: #a1a1aa; font-size: 8px; }
    @media print {
      body { padding: 10px 14px; }
      @page { size: A4 landscape; margin: 10mm; }
    }
  </style>
</head>
<body>
  <div class="header">
    <div class="brand">TransitOps<span>Smart Transport Operations Platform</span></div>
    <div class="meta">
      <div>Date: ${dateStr}</div>
      <div>Time: ${timeStr}</div>
      <div>Generated By: TransitOps</div>
    </div>
  </div>

  <h1>${title}</h1>

  <div class="summary">
    <div class="summary-item">Total Records: <strong>${rows.length}</strong></div>
    ${activeFilters ? `<div class="summary-item">Filters: ${activeFilters}</div>` : ""}
  </div>

  <table>
    <thead>
      <tr>${headers.map((h) => `<th>${h}</th>`).join("")}</tr>
    </thead>
    <tbody>${tableRows}</tbody>
  </table>

  <div class="footer">
    <span>TransitOps Smart Transport Operations Platform</span>
    <span>Exported: ${dateStr} ${timeStr}</span>
  </div>
</body>
</html>`;

  const win = window.open("", "_blank", "width=1100,height=750");
  if (!win) {
    throw new Error("Popup blocked. Please allow popups for this site and try again.");
  }
  win.document.write(html);
  win.document.close();
  win.document.title = filename;
  // Give the browser a moment to render before triggering print
  setTimeout(() => {
    win.print();
  }, 400);
}

// ─── Exports ──────────────────────────────────────────────────────────────────

/**
 * 1. Export Vehicles to PDF
 */
export function exportVehiclePDF(vehicles: any[], filters?: Record<string, string>) {
  if (!vehicles || vehicles.length === 0) throw new Error("No data available to export.");

  const headers = [
    "Registration No.",
    "Vehicle Model",
    "Type",
    "Capacity",
    "Odometer",
    "Acquisition Cost",
    "Status",
    "Fuel Cost",
    "Maintenance Cost",
    "Operational Cost",
  ];

  const rows = vehicles.map((v) => {
    const fuelCost = Number(v.fuelCost || 0);
    const maintenanceCost = Number(v.maintenanceCost || 0);
    const operationalCost = Number(v.operationalCost || 0);
    return [
      v.regNo || "—",
      v.modelName || "—",
      v.type || "—",
      v.capacityKg ? `${Number(v.capacityKg).toLocaleString()} kg` : "0 kg",
      v.odometerKm ? `${Number(v.odometerKm).toLocaleString()} km` : "0 km",
      v.acquisitionCost ? formatCurrency(Number(v.acquisitionCost)) : "$0",
      v.status || "—",
      formatCurrency(fuelCost),
      formatCurrency(maintenanceCost),
      formatCurrency(operationalCost),
    ];
  });

  const today = new Date().toISOString().split("T")[0];
  printReport("Vehicles Operational Report", headers, rows, `vehicles-report-${today}.pdf`, filters);
}

/**
 * 2. Export Drivers to PDF
 */
export function exportDriverPDF(drivers: Driver[], filters?: Record<string, string>) {
  if (!drivers || drivers.length === 0) throw new Error("No data available to export.");

  const headers = [
    "Driver Name",
    "License Number",
    "Category",
    "License Expiry",
    "Contact",
    "Safety Score",
    "Status",
  ];

  const rows = drivers.map((d) => [
    d.name || "—",
    d.licenseNo || "—",
    d.category || "—",
    formatDate(d.licenseExpiry),
    d.contact || "—",
    d.safetyScore !== undefined ? `${d.safetyScore} / 100` : "—",
    d.status || "—",
  ]);

  const today = new Date().toISOString().split("T")[0];
  printReport("Drivers Directory Report", headers, rows, `drivers-report-${today}.pdf`, filters);
}

/**
 * 3. Export Trips to PDF
 */
export function exportTripPDF(trips: Trip[], filters?: Record<string, string>) {
  if (!trips || trips.length === 0) throw new Error("No data available to export.");

  const headers = [
    "Trip ID",
    "Source",
    "Destination",
    "Vehicle",
    "Driver",
    "Cargo Weight",
    "Distance",
    "Status",
    "Dispatched",
    "Completed",
  ];

  const rows = trips.map((t) => [
    t.tripCode || `ID: ${t.id}`,
    t.source || "—",
    t.destination || "—",
    t.vehicle?.regNo || "—",
    t.driver?.name || "—",
    t.cargoWeightKg ? `${Number(t.cargoWeightKg).toLocaleString()} kg` : "0 kg",
    t.actualDistanceKm ? `${Number(t.actualDistanceKm).toLocaleString()} km` : "—",
    t.status || "—",
    formatDate(t.dispatchedAt),
    formatDate(t.completedAt),
  ]);

  const today = new Date().toISOString().split("T")[0];
  printReport("Trip Log & Dispatch Report", headers, rows, `trips-report-${today}.pdf`, filters);
}

/**
 * 4. Export Fuel & Expenses to PDF
 */
export function exportExpensePDF(
  records: any[],
  type: "FUEL" | "EXPENSE",
  filters?: Record<string, string>
) {
  if (!records || records.length === 0) throw new Error("No data available to export.");

  const headers = [
    "Vehicle",
    "Fuel Liters",
    "Fuel Cost",
    "Maintenance Cost",
    "Toll Charges",
    "Other Expenses",
    "Operational Cost",
    "Date",
  ];

  const rows = records.map((r) => {
    if (type === "FUEL") {
      const liters = Number(r.liters || 0);
      const fuelCost = Number(r.fuelCost || 0);
      return [
        r.vehicle?.regNo || "—",
        `${liters.toLocaleString()} L`,
        formatCurrency(fuelCost),
        "$0",
        "$0",
        "$0",
        formatCurrency(fuelCost),
        formatDate(r.logDate),
      ];
    } else {
      const toll = Number(r.tollCost || 0);
      const other = Number(r.otherCost || 0);
      return [
        r.vehicle?.regNo || "—",
        "0 L",
        "$0",
        "$0",
        formatCurrency(toll),
        formatCurrency(other),
        formatCurrency(toll + other),
        formatDate(r.createdAt),
      ];
    }
  });

  const today = new Date().toISOString().split("T")[0];
  printReport(
    type === "FUEL" ? "Fuel Consumption Report" : "Trip Expenditures Report",
    headers,
    rows,
    `expenses-report-${today}.pdf`,
    filters
  );
}

/**
 * 5. Export Analytics to PDF
 */
export function exportAnalyticsPDF(vehicles: any[], filters?: Record<string, string>) {
  if (!vehicles || vehicles.length === 0) throw new Error("No data available to export.");

  const headers = [
    "Vehicle",
    "Fleet Utilization",
    "Fuel Efficiency",
    "Fuel Cost",
    "Maintenance Cost",
    "Operational Cost",
    "Revenue",
    "ROI %",
  ];

  const rows = vehicles.map((v) => {
    const utilization = v.status === "ON_TRIP" ? "100%" : "0%";
    const totalDistance = v.trips
      ? v.trips
          .filter((t: any) => t.status === "COMPLETED")
          .reduce((s: number, t: any) => s + Number(t.actualDistanceKm || 0), 0)
      : 0;
    const totalLiters = v.fuelLogs
      ? v.fuelLogs.reduce((s: number, l: any) => s + Number(l.liters || 0), 0)
      : 0;
    const efficiency = totalLiters > 0 ? `${(totalDistance / totalLiters).toFixed(2)} km/L` : "0.00 km/L";

    const fuelCost = Number(v.fuelCost || 0);
    const maintenanceCost = Number(v.maintenanceCost || 0);
    const operationalCost = Number(v.operationalCost || 0);
    const totalRevenue = v.trips
      ? v.trips.reduce((s: number, t: any) => s + Number(t.revenue?.revenue || 0), 0)
      : 0;

    const acqCost = Number(v.acquisitionCost || 0);
    const roi =
      acqCost > 0
        ? `${(((totalRevenue - (fuelCost + maintenanceCost)) / acqCost) * 100).toFixed(1)}%`
        : "0.0%";

    return [
      v.regNo || "—",
      utilization,
      efficiency,
      formatCurrency(fuelCost),
      formatCurrency(maintenanceCost),
      formatCurrency(operationalCost),
      formatCurrency(totalRevenue),
      roi,
    ];
  });

  const today = new Date().toISOString().split("T")[0];
  printReport("Fleet Analytics & ROI Report", headers, rows, `analytics-report-${today}.pdf`, filters);
}
