import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { Vehicle } from "@/types/vehicle";
import { Driver } from "@/types/driver";
import { Trip } from "@/types/trip";
import { FuelLog } from "@/types/fuel";
import { Expense } from "@/types/expense";

// Helper to format currency
const formatCurrency = (val: number) => {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(val);
};

// Helper to format dates to YYYY-MM-DD
const formatDate = (dateStr?: string | null) => {
  if (!dateStr) return "—";
  try {
    const d = new Date(dateStr);
    if (isNaN(d.getTime())) return "—";
    return d.toISOString().split("T")[0];
  } catch {
    return "—";
  }
};

/**
 * Shared layout generator for jspdf reports
 */
function generatePDFReport(
  title: string,
  headers: string[],
  rows: string[][],
  filename: string,
  filters?: Record<string, string>
) {
  const doc = new jsPDF({
    orientation: "landscape",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = 297;
  const pageHeight = 210;
  const margin = 15;

  // Add Header Branding
  doc.setFont("Helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(24, 24, 27); // zinc-900
  doc.text("TransitOps", margin, 20);

  doc.setFont("Helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(115, 115, 115); // zinc-500
  doc.text("Smart Transport Operations Platform", margin + 28, 17);

  // Dark line under branding header
  doc.setFillColor(39, 39, 42); // zinc-800
  doc.rect(margin, 23, pageWidth - (margin * 2), 1, "F");

  // Report Title
  doc.setFont("Helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(39, 39, 42);
  doc.text(title.toUpperCase(), margin, 32);

  // Metadata block (top right)
  const now = new Date();
  const dateStr = now.toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" });
  const timeStr = now.toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit", second: "2-digit" });

  doc.setFont("Helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(82, 82, 91); // zinc-600
  doc.text(`Date: ${dateStr}`, pageWidth - margin, 30, { align: "right" });
  doc.text(`Time: ${timeStr}`, pageWidth - margin, 34, { align: "right" });
  doc.text(`Generated By: TransitOps`, pageWidth - margin, 38, { align: "right" });

  let currentY = 44;

  // Total Records
  doc.setFont("Helvetica", "bold");
  doc.text(`Total Records: ${rows.length}`, margin, currentY);
  
  if (filters && Object.keys(filters).length > 0) {
    const filterParts = Object.entries(filters)
      .filter(([_, val]) => val && val !== "ALL" && val.trim() !== "")
      .map(([key, val]) => `${key}: ${val}`);
    if (filterParts.length > 0) {
      currentY += 4;
      doc.setFont("Helvetica", "normal");
      doc.text(`Applied Filters: [ ${filterParts.join(" | ")} ]`, margin, currentY);
    }
  }

  currentY += 6;

  // Generate Table
  autoTable(doc, {
    startY: currentY,
    head: [headers],
    body: rows,
    margin: { top: 25, bottom: 20, left: margin, right: margin },
    styles: {
      fontSize: 8,
      cellPadding: 3,
      valign: "middle",
      overflow: "linebreak",
      font: "Helvetica",
      textColor: [63, 63, 70], // zinc-700
    },
    headStyles: {
      fillColor: [39, 39, 42], // zinc-800
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
    alternateRowStyles: {
      fillColor: [250, 250, 250], // zinc-50
    },
  });

  // Footer pass
  const pageCount = doc.internal.pages.length - 1;
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont("Helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(115, 115, 115); // zinc-500
    doc.text("TransitOps Smart Transport Operations Platform", margin, pageHeight - 10);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, pageHeight - 10, { align: "right" });
  }

  doc.save(filename);
}

/**
 * 1. Export Vehicles to PDF
 */
export function exportVehiclePDF(vehicles: any[], filters?: Record<string, string>) {
  if (!vehicles || vehicles.length === 0) {
    throw new Error("No data available to export.");
  }

  const headers = [
    "Registration Number",
    "Vehicle Model",
    "Vehicle Type",
    "Maximum Capacity",
    "Odometer",
    "Acquisition Cost",
    "Status",
    "Fuel Cost",
    "Maintenance Cost",
    "Operational Cost"
  ];

  const rows = vehicles.map((v) => {
    const fuelCost = Number(v.fuelCost || 0);
    const maintenanceCost = Number(v.maintenanceCost || 0);
    const operationalCost = Number(v.operationalCost || 0);

    return [
      v.regNo || "—",
      v.modelName || "—",
      v.type || "—",
      v.capacityKg ? `${Number(v.capacityKg).toLocaleString()} kg` : "0 kg",
      v.odometerKm ? `${Number(v.odometerKm).toLocaleString()} km` : "0 km",
      v.acquisitionCost ? formatCurrency(Number(v.acquisitionCost)) : "$0",
      v.status || "—",
      formatCurrency(fuelCost),
      formatCurrency(maintenanceCost),
      formatCurrency(operationalCost)
    ];
  });

  const today = new Date().toISOString().split("T")[0];
  generatePDFReport("Vehicles Operational Report", headers, rows, `vehicles-report-${today}.pdf`, filters);
}

/**
 * 2. Export Drivers to PDF
 */
export function exportDriverPDF(drivers: Driver[], filters?: Record<string, string>) {
  if (!drivers || drivers.length === 0) {
    throw new Error("No data available to export.");
  }

  const headers = [
    "Driver Name",
    "License Number",
    "License Category",
    "License Expiry Date",
    "Contact Number",
    "Safety Score",
    "Status"
  ];

  const rows = drivers.map((d) => [
    d.name || "—",
    d.licenseNo || "—",
    d.category || "—",
    formatDate(d.licenseExpiry),
    d.contact || "—",
    d.safetyScore !== undefined ? `${d.safetyScore} / 100` : "—",
    d.status || "—"
  ]);

  const today = new Date().toISOString().split("T")[0];
  generatePDFReport("Drivers Directory Report", headers, rows, `drivers-report-${today}.pdf`, filters);
}

/**
 * 3. Export Trips to PDF
 */
export function exportTripPDF(trips: Trip[], filters?: Record<string, string>) {
  if (!trips || trips.length === 0) {
    throw new Error("No data available to export.");
  }

  const headers = [
    "Trip ID",
    "Source",
    "Destination",
    "Vehicle",
    "Driver",
    "Cargo Weight",
    "Distance",
    "Trip Status",
    "Dispatch Date",
    "Completion Date"
  ];

  const rows = trips.map((t) => [
    t.tripCode || `ID: ${t.id}`,
    t.source || "—",
    t.destination || "—",
    t.vehicle?.regNo || "—",
    t.driver?.name || "—",
    t.cargoWeightKg ? `${Number(t.cargoWeightKg).toLocaleString()} kg` : "0 kg",
    t.actualDistanceKm ? `${Number(t.actualDistanceKm).toLocaleString()} km` : "—",
    t.status || "—",
    formatDate(t.dispatchedAt),
    formatDate(t.completedAt)
  ]);

  const today = new Date().toISOString().split("T")[0];
  generatePDFReport("Trip Log & Dispatch Report", headers, rows, `trips-report-${today}.pdf`, filters);
}

/**
 * 4. Export Fuel & Expenses to PDF
 */
export function exportExpensePDF(
  records: any[],
  type: "FUEL" | "EXPENSE",
  filters?: Record<string, string>
) {
  if (!records || records.length === 0) {
    throw new Error("No data available to export.");
  }

  const headers = [
    "Vehicle",
    "Fuel Liters",
    "Fuel Cost",
    "Maintenance Cost",
    "Toll Charges",
    "Other Expenses",
    "Operational Cost",
    "Date"
  ];

  const rows = records.map((r) => {
    if (type === "FUEL") {
      const fuelLiters = Number(r.liters || 0);
      const fuelCost = Number(r.fuelCost || 0);
      return [
        r.vehicle?.regNo || "—",
        `${fuelLiters.toLocaleString()} L`,
        formatCurrency(fuelCost),
        "$0",
        "$0",
        "$0",
        formatCurrency(fuelCost),
        formatDate(r.logDate)
      ];
    } else {
      const tollCost = Number(r.tollCost || 0);
      const otherCost = Number(r.otherCost || 0);
      const opCost = tollCost + otherCost;
      return [
        r.vehicle?.regNo || "—",
        "0 L",
        "$0",
        "$0", // Maintenance Cost is 0 unless linked
        formatCurrency(tollCost),
        formatCurrency(otherCost),
        formatCurrency(opCost),
        formatDate(r.createdAt)
      ];
    }
  });

  const today = new Date().toISOString().split("T")[0];
  generatePDFReport(
    type === "FUEL" ? "Fuel Consumption Report" : "Trip Expenditures Report",
    headers,
    rows,
    `expenses-report-${today}.pdf`,
    filters
  );
}

/**
 * 5. Export Analytics to PDF
 */
export function exportAnalyticsPDF(vehicles: any[], filters?: Record<string, string>) {
  if (!vehicles || vehicles.length === 0) {
    throw new Error("No data available to export.");
  }

  const headers = [
    "Vehicle",
    "Fleet Utilization %",
    "Fuel Efficiency (km/L)",
    "Fuel Cost",
    "Maintenance Cost",
    "Operational Cost",
    "Revenue",
    "Vehicle ROI %"
  ];

  const rows = vehicles.map((v) => {
    // 1. Fleet Utilization
    const fleetUtilizationStr = v.status === "ON_TRIP" ? "100%" : "0%";

    // 2. Fuel Efficiency
    // total actual distance / total liters
    const totalDistance = v.trips
      ? v.trips.filter((t: any) => t.status === "COMPLETED").reduce((sum: number, t: any) => sum + Number(t.actualDistanceKm || 0), 0)
      : 0;
    const totalLiters = v.fuelLogs
      ? v.fuelLogs.reduce((sum: number, l: any) => sum + Number(l.liters || 0), 0)
      : 0;
    const fuelEfficiencyStr = totalLiters > 0 ? `${(totalDistance / totalLiters).toFixed(2)} km/L` : "0.00 km/L";

    // 3. Costs
    const fuelCost = Number(v.fuelCost || 0);
    const maintenanceCost = Number(v.maintenanceCost || 0);
    const operationalCost = Number(v.operationalCost || 0);

    // 4. Revenue
    const totalRevenue = v.trips
      ? v.trips.reduce((sum: number, t: any) => sum + Number(t.revenue?.revenue || 0), 0)
      : 0;

    // 5. ROI %
    let roiStr = "0.0%";
    const acqCost = Number(v.acquisitionCost || 0);
    if (acqCost > 0) {
      const roi = ((totalRevenue - (fuelCost + maintenanceCost)) / acqCost) * 100;
      roiStr = `${roi.toFixed(1)}%`;
    }

    return [
      v.regNo || "—",
      fleetUtilizationStr,
      fuelEfficiencyStr,
      formatCurrency(fuelCost),
      formatCurrency(maintenanceCost),
      formatCurrency(operationalCost),
      formatCurrency(totalRevenue),
      roiStr
    ];
  });

  const today = new Date().toISOString().split("T")[0];
  generatePDFReport("Fleet Analytics & ROI Report", headers, rows, `analytics-report-${today}.pdf`, filters);
}
